version: '3.8'

services:
  api:
    container_name: cryptodistrict_api
    restart: always
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    env_file:
      - .env.development
    command: npm run start:dev
    volumes:
      - ./:/usr/src/cryptodistrict_api
      - /usr/src/cryptodistrict_api/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - cryptodistrict-api-network
  db:
    image: postgres
    container_name: cryptodistrict-api-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: cryptodistrict
    volumes:
      - /:/data/postgres
    networks:
      - cryptodistrict-api-network

networks:
  cryptodistrict-api-network:
    driver: bridge
